package net.caravidro.wayaround.ecology;

import java.util.*;

/** Generated by tools/generate_fish_habitats.py; rules are independent of Minecraft bootstrap. */
public enum FishHabitat {
    OCEAN(List.of("minecraft:ocean"), List.of("minecraft:cod", "wayaround:sardine", "wayaround:sunfish", "wayaround:flying_fish")),
    WARM_REEF(List.of("minecraft:warm_ocean"), List.of("minecraft:tropical_fish", "minecraft:pufferfish", "wayaround:clownfish", "wayaround:moray_eel", "wayaround:reef_shark")),
    LUKEWARM_COAST(List.of("minecraft:lukewarm_ocean"), List.of("wayaround:sardine", "wayaround:flying_fish", "wayaround:barracuda", "wayaround:seahorse", "wayaround:manta_ray")),
    COLD_OCEAN(List.of("minecraft:cold_ocean"), List.of("minecraft:cod", "minecraft:salmon", "wayaround:sardine")),
    FROZEN_OCEAN(List.of("minecraft:frozen_ocean"), List.of("minecraft:cod", "minecraft:salmon", "wayaround:icefish")),
    DEEP_TEMPERATE(List.of("minecraft:deep_ocean"), List.of("minecraft:cod", "wayaround:sardine", "wayaround:lanternfish", "wayaround:oarfish", "wayaround:anglerfish")),
    DEEP_COLD(List.of("minecraft:deep_cold_ocean"), List.of("minecraft:cod", "minecraft:salmon", "wayaround:lanternfish", "wayaround:oarfish", "wayaround:anglerfish")),
    DEEP_FROZEN(List.of("minecraft:deep_frozen_ocean"), List.of("minecraft:cod", "wayaround:icefish", "wayaround:lanternfish", "wayaround:anglerfish")),
    DEEP_LUKEWARM(List.of("minecraft:deep_lukewarm_ocean"), List.of("wayaround:sardine", "wayaround:flying_fish", "wayaround:lanternfish", "wayaround:oarfish", "wayaround:anglerfish")),
    ANTARCTIC_SEA(List.of("wayaround:southern_ocean"), List.of("wayaround:icefish", "wayaround:toothfish", "wayaround:lanternfish")),
    ANTARCTIC_ICE(List.of("wayaround:antarctic_ice_sheet"), List.of("minecraft:cod", "wayaround:icefish", "wayaround:toothfish")),
    RIVER(List.of("minecraft:river"), List.of("minecraft:salmon", "wayaround:trout", "wayaround:perch", "wayaround:carp")),
    FROZEN_RIVER(List.of("minecraft:frozen_river"), List.of("minecraft:salmon", "wayaround:trout", "wayaround:perch")),
    SWAMP(List.of("minecraft:swamp"), List.of("wayaround:carp", "wayaround:catfish")),
    MANGROVE(List.of("minecraft:mangrove_swamp"), List.of("wayaround:archerfish", "wayaround:catfish", "wayaround:seahorse")),
    TROPICAL_LAKE(List.of("minecraft:jungle", "minecraft:sparse_jungle", "minecraft:bamboo_jungle"), List.of("wayaround:carp", "wayaround:catfish", "wayaround:archerfish")),
    DRY_LAKE(List.of("minecraft:desert", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:windswept_savanna", "minecraft:badlands", "minecraft:eroded_badlands", "minecraft:wooded_badlands"), List.of("wayaround:carp", "wayaround:catfish")),
    COLD_LAKE(List.of("minecraft:taiga", "minecraft:old_growth_pine_taiga", "minecraft:old_growth_spruce_taiga", "minecraft:snowy_taiga", "minecraft:snowy_plains", "minecraft:ice_spikes", "minecraft:grove", "minecraft:snowy_slopes", "minecraft:frozen_peaks", "minecraft:jagged_peaks", "minecraft:stony_peaks", "minecraft:windswept_hills", "minecraft:windswept_gravelly_hills", "minecraft:windswept_forest", "minecraft:snowy_beach", "minecraft:stony_shore"), List.of("wayaround:trout", "wayaround:perch")),
    TEMPERATE_LAKE(List.of("minecraft:plains", "minecraft:sunflower_plains", "minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:old_growth_birch_forest", "minecraft:dark_forest", "minecraft:meadow", "minecraft:cherry_grove", "minecraft:mushroom_fields", "minecraft:beach"), List.of("wayaround:carp", "wayaround:perch", "wayaround:catfish")),
    CAVE_POOL(List.of("minecraft:lush_caves", "minecraft:dripstone_caves"), List.of("wayaround:catfish", "wayaround:perch"));
    public final List<String> biomes, fish;
    FishHabitat(List<String> biomes, List<String> fish) { this.biomes = biomes; this.fish = fish; }
    private static final Map<String, FishHabitat> BY_BIOME = new HashMap<>();
    private static final Set<String> MANAGED = new HashSet<>();
    static {
        for (var habitat : values()) {
            for (String biome : habitat.biomes) {
                if (BY_BIOME.put(biome, habitat) != null) throw new IllegalStateException("Overlapping habitat: " + biome);
            }
            MANAGED.addAll(habitat.fish);
        }
    }
    public static FishHabitat forBiome(String biome) { return BY_BIOME.get(biome); }
    public static boolean managed(String fish) { return MANAGED.contains(fish); }
    public boolean permits(String species, int depth) {
        if (!fish.contains(species)) return false;
        return switch (species) {
            case "wayaround:anglerfish" -> depth >= 55;
            case "wayaround:lanternfish" -> depth >= 28;
            case "wayaround:oarfish" -> depth >= 20;
            case "wayaround:toothfish" -> depth >= 8;
            // Surface visitors must not populate the bottom of the trenches.
            case "wayaround:sardine", "wayaround:flying_fish", "minecraft:cod", "minecraft:salmon", "wayaround:icefish" -> depth <= 30;
            default -> true;
        };
    }
}
