package net.caravidro.wayaround.war.outpost;

import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.monster.Zombie;
import net.minecraft.world.item.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.phys.*;
import net.neoforged.neoforge.gametest.*;

@GameTestHolder("wayaround_outpost")
@PrefixGameTestTemplate(false)
public final class OutpostGameTests {
    private static FieldDeviceBlockEntity device(GameTestHelper h,FieldDeviceBlock block){
        var p=h.absolutePos(new BlockPos(7,5,7));var l=h.getLevel();for(int x=-4;x<=4;x++)for(int z=-4;z<=4;z++)for(int y=-1;y<=3;y++)l.setBlock(p.offset(x,y,z),y<0?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),18);l.setBlock(p,block.defaultBlockState(),18);return (FieldDeviceBlockEntity)l.getBlockEntity(p);
    }
    private static Zombie target(GameTestHelper h,Vec3 at){var z=new Zombie(h.getLevel());z.setNoAi(true);z.setNoGravity(true);z.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));z.setPos(at);h.getLevel().addFreshEntity(z);return z;}
    private static ServerPlayer player(GameTestHelper h){var p=h.makeMockServerPlayerInLevel();var c=new net.minecraft.network.Connection(net.minecraft.network.protocol.PacketFlow.SERVERBOUND);new io.netty.channel.embedded.EmbeddedChannel(c);p.connection=new net.minecraft.server.network.ServerGamePacketListenerImpl(h.getLevel().getServer(),c,p,net.minecraft.server.network.CommonListenerCookie.createInitial(p.getGameProfile(),false)){
        @Override public void send(net.minecraft.network.protocol.Packet<?> p){}
        @Override public void send(net.minecraft.network.protocol.Packet<?> p,net.minecraft.network.PacketSendListener l){}
    };p.setGameMode(GameType.SURVIVAL);return p;}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void contactMinePhysicallyExplodesOnTouch(GameTestHelper h){var d=device(h,OutpostContent.CONTACT_MINE.get());var pos=d.getBlockPos();var z=target(h,Vec3.atBottomCenterOf(pos).add(0,.2,0));d.touch(z);h.assertTrue(h.getLevel().getBlockState(pos).isAir(),"Touch consumes the mine");h.assertTrue(z.getHealth()<20||!z.isAlive(),"Real explosion damages its victim");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void standaloneWaitsThenExplodesWhenVictimMoves(GameTestHelper h){var d=device(h,OutpostContent.STANDALONE_MINE.get());var pos=d.getBlockPos();var z=target(h,Vec3.atBottomCenterOf(pos).add(0,.2,0));d.touch(z);h.assertTrue(z.getUUID().equals(d.victim()),"Pressure captures the actual victim");h.runAfterDelay(12,()->{h.assertTrue(h.getLevel().getBlockState(pos).is(OutpostContent.STANDALONE_MINE.get()),"Looking/staying still does not trigger detonation");z.setPos(z.position().add(.3,0,0));});h.runAfterDelay(16,()->{h.assertTrue(h.getLevel().getBlockState(pos).isAir(),"Moving the latched victim detonates through the BE tick");h.succeed();});}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void standaloneDetectsSlotAndOffhandChanges(GameTestHelper h){var p=h.makeMockPlayer(GameType.SURVIVAL);p.setPos(Vec3.atCenterOf(h.absolutePos(new BlockPos(2,3,2))));var at=p.position();var main=p.getMainHandItem().copy();var off=p.getOffhandItem().copy();int slot=p.getInventory().selected;p.setYRot(130);h.assertTrue(!FieldDeviceBlockEntity.disturbed(p,at,slot,main,off),"Head turns are safe");p.getInventory().selected=(slot+1)%9;h.assertTrue(FieldDeviceBlockEntity.disturbed(p,at,slot,main,off),"Even an identical empty hotbar slot change trips the sensor");p.getInventory().selected=slot;p.setItemInHand(InteractionHand.OFF_HAND,new ItemStack(Items.STICK));h.assertTrue(FieldDeviceBlockEntity.disturbed(p,at,slot,main,off),"Offhand changes are detected");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void armedMineAndCoverSurviveSave(GameTestHelper h){var d=device(h,OutpostContent.STANDALONE_MINE.get());var z=target(h,Vec3.atBottomCenterOf(d.getBlockPos()).add(0,.2,0));d.touch(z);h.assertTrue(d.camouflage(),"Cover applies once");h.assertTrue(!d.camouflage(),"No repeated camo consumption");var data=d.saveWithoutMetadata(h.getLevel().registryAccess());var restored=new FieldDeviceBlockEntity(d.getBlockPos(),d.getBlockState());restored.loadWithComponents(data,h.getLevel().registryAccess());h.assertTrue(z.getUUID().equals(restored.victim())&&restored.cover().is(Blocks.STONE),"Victim and actual ground material persist");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void spikesHurtOnPhysicalContact(GameTestHelper h){var d=device(h,OutpostContent.SPIKE_BARRAGE.get());var z=target(h,Vec3.atCenterOf(d.getBlockPos()));d.touch(z);h.assertTrue(z.getHealth()<20,"Spikes damage a touching living entity");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void gunRequiresBarrelAndReturnsRealAmmunition(GameTestHelper h){var d=device(h,OutpostContent.FIXED_MACHINE_GUN.get());var p=player(h);var pos=d.getBlockPos();p.setPos(Vec3.atBottomCenterOf(pos).add(0,0,1.4));h.assertTrue(!d.fire(p),"A bare stand cannot shoot");p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(OutpostContent.GUN_BARREL.get()));d.interact(p,InteractionHand.MAIN_HAND);h.assertTrue(p.getMainHandItem().isEmpty()&&d.getBlockState().getValue(FieldDeviceBlock.BARREL),"Installed assembly consumes one real part");p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.IRON_NUGGET,12));d.interact(p,InteractionHand.MAIN_HAND);h.assertTrue(d.ammo()==12&&p.getMainHandItem().isEmpty(),"Loaded ammunition is real inventory");h.getLevel().removeBlock(pos,false);var drops=h.getLevel().getEntitiesOfClass(net.minecraft.world.entity.item.ItemEntity.class,new AABB(pos).inflate(2));int ammo=drops.stream().filter(e->e.getItem().is(Items.IRON_NUGGET)).mapToInt(e->e.getItem().getCount()).sum();h.assertTrue(ammo==12&&drops.stream().filter(e->e.getItem().is(OutpostContent.GUN_BARREL.get())).count()==1,"Removing the stand returns parts/ammo once");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void gunMountFiresExistingProjectileAndEjectsOnRemoval(GameTestHelper h){var d=device(h,OutpostContent.FIXED_MACHINE_GUN.get());var p=player(h);var pos=d.getBlockPos();p.setPos(Vec3.atBottomCenterOf(pos).add(0,0,1.4));p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(OutpostContent.GUN_BARREL.get()));d.interact(p,InteractionHand.MAIN_HAND);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.IRON_NUGGET,12));d.interact(p,InteractionHand.MAIN_HAND);p.setItemInHand(InteractionHand.MAIN_HAND,ItemStack.EMPTY);d.interact(p,InteractionHand.MAIN_HAND);h.assertTrue(d.operating(p),"Operator rides a fixed physical seat");h.assertTrue(d.fire(p)&&d.ammo()==11,"Mounted trigger spends exactly one shot");h.assertTrue(!h.getLevel().getEntitiesOfClass(net.caravidro.wayaround.war.WarProjectileEntity.class,new AABB(pos).inflate(4)).isEmpty(),"Same projectile as War Without Reason/Infinity");h.getLevel().removeBlock(pos,false);h.assertTrue(!p.isPassenger(),"Removing the gun releases the operator");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=150)
    public static void passageAlarmOutputsRedstoneThenResets(GameTestHelper h){var d=device(h,OutpostContent.PASSAGE_ALARM.get());var pos=d.getBlockPos();var z=target(h,Vec3.atCenterOf(pos).add(0,0,-3));h.runAfterDelay(12,()->{h.assertTrue(h.getLevel().getBestNeighborSignal(pos.below())>0,"Intruder crossing generates an actual redstone output");z.discard();});h.runAfterDelay(60,()->{h.assertTrue(!h.getLevel().getBlockState(pos).getValue(FieldDeviceBlock.ACTIVE),"Alarm clears after passage, not a permanent on switch");h.succeed();});}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void barricadeStopsProjectileClip(GameTestHelper h){var d=device(h,OutpostContent.FIELD_BARRICADE.get());var mid=Vec3.atBottomCenterOf(d.getBlockPos()).add(0,.5,0);var hit=h.getLevel().clip(new ClipContext(mid.add(0,0,2),mid.add(0,0,-2),ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,null));h.assertTrue(hit.getType()==HitResult.Type.BLOCK&&hit.getBlockPos().equals(d.getBlockPos()),"Cover physically blocks the trajectory");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void remoteChargeIsOwnedAndConsumesItself(GameTestHelper h){var d=device(h,OutpostContent.REMOTE_CHARGE.get());var p=player(h);p.setPos(Vec3.atBottomCenterOf(d.getBlockPos()).add(2,0,0));d.placed(p);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(OutpostContent.CONTROLLER.get()));d.interact(p,InteractionHand.MAIN_HAND);h.assertTrue(RemoteControllerItem.data(p.getMainHandItem()).getLong("Charge")==d.getBlockPos().asLong(),"Controller binds to a physical charge");p.setShiftKeyDown(true);var at=d.getBlockPos();OutpostContent.CONTROLLER.get().use(h.getLevel(),p,InteractionHand.MAIN_HAND);h.assertTrue(h.getLevel().getBlockState(at).isAir(),"Owner's remote action removes/consumes charge");h.succeed();}
    private static OutpostDroneEntity drone(GameTestHelper h,ServerPlayer p,boolean impact){var d=OutpostContent.DRONE.get().create(h.getLevel());d.configure(p.getUUID(),impact,6000);d.setPos(Vec3.atCenterOf(h.absolutePos(new BlockPos(3,6,3))));h.getLevel().addFreshEntity(d);var foot=d.blockPosition().offset(2,0,0);h.getLevel().setBlock(foot.below(),Blocks.STONE.defaultBlockState(),18);h.getLevel().setBlock(foot,Blocks.AIR.defaultBlockState(),18);h.getLevel().setBlock(foot.above(),Blocks.AIR.defaultBlockState(),18);p.setPos(Vec3.atBottomCenterOf(foot));p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(OutpostContent.CONTROLLER.get()));RemoteControllerItem.bindDrone(p.getMainHandItem(),d);return d;}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void remoteFlightDoesNotTeleportOrProtectPilot(GameTestHelper h){var p=player(h);var d=drone(h,p,false);var body=p.position();OutpostRemote.start(p,d);h.assertTrue(OutpostRemote.active(p)&&OutpostRemote.cameraActive(p),"Actual observation session enables existing media");h.assertTrue(!p.isInvulnerable()&&!p.noPhysics,"Pilot remains physical and vulnerable");h.assertTrue(d.controls(p,1,0,1,0,0),"Authorized input accepted");var before=d.position();h.runAfterDelay(5,()->{h.assertTrue(d.position().distanceToSqr(before)>.01,"Drone moves from accepted controls");h.assertTrue(p.position().distanceToSqr(body)<.001,"Camera flight does not move player body");OutpostRemote.stop(p);h.assertTrue(!OutpostRemote.active(p),"Stop clears remote session");h.succeed();});}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void droneRejectsSpoofedAndNonFiniteControls(GameTestHelper h){var p=player(h);var d=drone(h,p,false);h.assertTrue(!d.controls(p,1,0,0,0,0),"Ownership alone does not permit input without session");OutpostRemote.start(p,d);h.assertTrue(!d.controls(p,1,0,0,Float.NaN,0),"Non-finite orientation is rejected");p.setItemInHand(InteractionHand.MAIN_HAND,ItemStack.EMPTY);h.assertTrue(!d.controls(p,1,0,0,0,0),"Dropping controller revokes authority");OutpostRemote.stop(p);h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void droneChargeOwnerAndPackedBatterySurviveSave(GameTestHelper h){var p=player(h);var d=drone(h,p,true);d.configure(p.getUUID(),true,1234);var n=new CompoundTag();d.saveWithoutId(n);var restored=OutpostContent.DRONE.get().create(h.getLevel());restored.load(n);h.assertTrue(restored.owned(p)&&restored.impact()&&restored.battery()==1234,"Saved drone retains owner/type/energy");h.assertTrue(RemoteControllerItem.data(restored.packed()).getInt("Battery")==1234,"Recovery/redeployment cannot refill energy for free");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void launchedDroneExplodesOnActualWallContact(GameTestHelper h){var p=player(h);var d=drone(h,p,true);d.setYRot(0);d.setXRot(0);var wall=d.blockPosition().offset(0,0,3);h.getLevel().setBlock(wall,Blocks.STONE.defaultBlockState(),18);OutpostRemote.start(p,d);d.launch(p);h.assertTrue(d.launched()&&!OutpostRemote.active(p),"Launch releases the operator, missile continues physically");h.runAfterDelay(8,()->{h.assertTrue(d.isRemoved(),"Actual swept collision consumes the impact drone");h.succeed();});}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=100)
    public static void droneRadioHasFiniteRange(GameTestHelper h){var p=player(h);var d=drone(h,p,false);p.setPos(d.position().add(97,0,0));OutpostRemote.start(p,d);h.assertTrue(!OutpostRemote.active(p),"Out-of-range entity cannot be piloted/force-loaded");h.succeed();}
    @GameTest(template="assembly_test",batch="outpost",timeoutTicks=1500)
    public static void smokeAndFlareActivateAndExpire(GameTestHelper h){var l=h.getLevel();var at=Vec3.atCenterOf(h.absolutePos(new BlockPos(4,6,4)));var smoke=OutpostContent.CANISTER.get().create(l);smoke.configure(false);smoke.setPos(at);l.addFreshEntity(smoke);var flare=OutpostContent.CANISTER.get().create(l);flare.configure(true);flare.setPos(at.add(2,0,0));l.addFreshEntity(flare);h.runAfterDelay(40,()->h.assertTrue(smoke.active()&&flare.active()&&!smoke.flare()&&flare.flare(),"Canisters activate after physical flight/fuse"));h.runAfterDelay(440,()->h.assertTrue(smoke.isRemoved()&&!flare.isRemoved(),"Smoke has a finite shorter lifetime"));h.runAfterDelay(1250,()->{h.assertTrue(flare.isRemoved(),"Flare also expires without permanent lights/entities");h.succeed();});}
}
