"""Regenerate the reviewed habitat manifest, Java rules and biome spawn modifiers."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'src/main/resources/data/wayaround'
# All fish in these lists count toward the 2..5 limit; other aquatic animals do not.
REGIONS = [
 ('ocean', ['ocean'], ['cod','sardine','sunfish','flying_fish']),
 ('warm_reef', ['warm_ocean'], ['tropical_fish','pufferfish','clownfish','moray_eel','reef_shark']),
 ('lukewarm_coast', ['lukewarm_ocean'], ['sardine','flying_fish','barracuda','seahorse','manta_ray']),
 ('cold_ocean', ['cold_ocean'], ['cod','salmon','sardine']),
 ('frozen_ocean', ['frozen_ocean'], ['cod','salmon','icefish']),
 ('deep_temperate', ['deep_ocean'], ['cod','sardine','lanternfish','oarfish','anglerfish']),
 ('deep_cold', ['deep_cold_ocean'], ['cod','salmon','lanternfish','oarfish','anglerfish']),
 ('deep_frozen', ['deep_frozen_ocean'], ['cod','icefish','lanternfish','anglerfish']),
 ('deep_lukewarm', ['deep_lukewarm_ocean'], ['sardine','flying_fish','lanternfish','oarfish','anglerfish']),
 ('antarctic_sea', ['wayaround:southern_ocean'], ['icefish','toothfish','lanternfish']),
 ('antarctic_ice', ['wayaround:antarctic_ice_sheet'], ['cod','icefish','toothfish']),
 ('river', ['river'], ['salmon','trout','perch','carp']),
 ('frozen_river', ['frozen_river'], ['salmon','trout','perch']),
 ('swamp', ['swamp'], ['carp','catfish']),
 ('mangrove', ['mangrove_swamp'], ['archerfish','catfish','seahorse']),
 ('tropical_lake', ['jungle','sparse_jungle','bamboo_jungle'], ['carp','catfish','archerfish']),
 ('dry_lake', ['desert','savanna','savanna_plateau','windswept_savanna','badlands','eroded_badlands','wooded_badlands'], ['carp','catfish']),
 ('cold_lake', ['taiga','old_growth_pine_taiga','old_growth_spruce_taiga','snowy_taiga','snowy_plains','ice_spikes','grove','snowy_slopes','frozen_peaks','jagged_peaks','stony_peaks','windswept_hills','windswept_gravelly_hills','windswept_forest','snowy_beach','stony_shore'], ['trout','perch']),
 ('temperate_lake', ['plains','sunflower_plains','forest','flower_forest','birch_forest','old_growth_birch_forest','dark_forest','meadow','cherry_grove','mushroom_fields','beach'], ['carp','perch','catfish']),
 ('cave_pool', ['lush_caves','dripstone_caves'], ['catfish','perch']),
]
VANILLA = {'cod','salmon','pufferfish','tropical_fish'}
def fish_id(s): return ('minecraft:' if s in VANILLA else 'wayaround:') + s
def biome_id(s): return s if ':' in s else 'minecraft:' + s
# Avoid duplicate vanilla entries in biomes that already provide them.
EXISTING = {'cod': {'ocean','cold_ocean','deep_ocean','deep_cold_ocean','lukewarm_ocean','deep_lukewarm_ocean'},
 'salmon': {'river','frozen_river','cold_ocean','deep_cold_ocean','frozen_ocean','deep_frozen_ocean'},
 'pufferfish': {'warm_ocean','lukewarm_ocean','deep_lukewarm_ocean'},
 'tropical_fish': {'warm_ocean','lukewarm_ocean','deep_lukewarm_ocean','lush_caves'}}
manifest=[]; constants=[]
for name, biomes, fish in REGIONS:
 assert 2 <= len(fish) <= 5 and len(set(fish)) == len(fish)
 manifest.append({'region':name,'biomes':list(map(biome_id,biomes)),'fish':list(map(fish_id,fish))})
 constants.append('    '+name.upper()+'(List.of('+', '.join('"'+biome_id(b)+'"' for b in biomes)+'), List.of('+', '.join('"'+fish_id(f)+'"' for f in fish)+'))')
 # A modifier per species/region permits additions only where vanilla lacks it.
 for f in fish:
  target=[biome_id(b) for b in biomes if b not in EXISTING.get(f,set())]
  if not target: continue
  rare=f in {'anglerfish','oarfish','toothfish','sunfish','reef_shark','manta_ray','moray_eel'}
  d={'type':'neoforge:add_spawns','biomes':target,'spawners':{'type':fish_id(f),'weight':3 if rare else 10,'minCount':1 if rare else 2,'maxCount':2 if rare else 5}}
  (DATA/f'neoforge/biome_modifier/regional_{name}_{f}.json').write_text(json.dumps(d,indent=2)+'\n')
(ROOT/'docs/fish-habitats.json').write_text(json.dumps(manifest,indent=2)+'\n')
p=ROOT/'src/main/java/net/caravidro/wayaround/ecology/FishHabitat.java'
p.write_text('''package net.caravidro.wayaround.ecology;

import java.util.*;

/** Generated by tools/generate_fish_habitats.py; rules are independent of Minecraft bootstrap. */
public enum FishHabitat {
'''+',\n'.join(constants)+''';
    public final List<String> biomes, fish;
    FishHabitat(List<String> biomes, List<String> fish) { this.biomes = biomes; this.fish = fish; }
    private static final Map<String, FishHabitat> BY_BIOME = new HashMap<>();
    private static final Set<String> MANAGED = new HashSet<>();
    static {
        for (var habitat : values()) {
            for (String biome : habitat.biomes) {
                if (BY_BIOME.put(biome, habitat) != null) throw new IllegalStateException("Overlapping habitat: " + biome);
            }
            MANAGED.addAll(habitat.fish);
        }
    }
    public static FishHabitat forBiome(String biome) { return BY_BIOME.get(biome); }
    public static boolean managed(String fish) { return MANAGED.contains(fish); }
    public boolean permits(String species, int depth) {
        if (!fish.contains(species)) return false;
        return switch (species) {
            case "wayaround:anglerfish" -> depth >= 55;
            case "wayaround:lanternfish" -> depth >= 28;
            case "wayaround:oarfish" -> depth >= 20;
            case "wayaround:toothfish" -> depth >= 8;
            // Surface visitors must not populate the bottom of the trenches.
            case "wayaround:sardine", "wayaround:flying_fish", "minecraft:cod", "minecraft:salmon", "wayaround:icefish" -> depth <= 30;
            default -> true;
        };
    }
}
''')
# Replace broad original fish additions; preserve all non-fish animals and plants.
for file in ['add_sardines','add_sunfish','add_reef_sharks','add_manta_rays','add_barracudas','add_seahorses','add_oarfish','add_clownfish','add_flying_fish','add_lanternfish','add_moray_eels']:
 p=DATA/f'neoforge/biome_modifier/{file}.json'
 if p.exists(): p.unlink()
for file in ['more_ocean_fauna','more_river_fauna','more_warm_ocean_fauna']:
 p=DATA/f'neoforge/biome_modifier/{file}.json';d=json.loads(p.read_text());d['spawners']=[s for s in d['spawners'] if s['type'].removeprefix('minecraft:') not in VANILLA];p.write_text(json.dumps(d,indent=2)+'\n')
