package net.caravidro.wayaround.littleleaf;

import java.util.Set;
import net.caravidro.wayaround.WayAround;
import net.minecraft.core.*;
import net.minecraft.core.registries.Registries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.*;
import net.minecraft.server.level.*;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;

@EventBusSubscriber(modid=WayAround.MODID)
public final class ColonyTravel {
    public static final ResourceKey<Level> DIMENSION=ResourceKey.create(Registries.DIMENSION,ResourceLocation.fromNamespaceAndPath(WayAround.MODID,"little_leaf_world"));
    private static final String VISIT="WayAroundColonyVisit",COOLDOWN="WayAroundColonyTravelCooldown";
    public static void enter(ServerPlayer player,ColonyCoreBlockEntity core){
        if(player.isPassenger()||player.getScale()>.2||player.level().dimension().equals(DIMENSION)||cooldown(player))return;
        var inside=player.server.getLevel(DIMENSION);if(inside==null)return;
        var link=ColonyTransitData.get(player.server).activate(player.level().dimension(),core.getBlockPos());
        prepare(inside,link,core.species(),core.stage());
        var t=new CompoundTag();t.putString("Dimension",player.level().dimension().location().toString());t.putLong("Source",core.getBlockPos().asLong());t.putDouble("BaseScale",player.getAttribute(Attributes.SCALE).getBaseValue());
        player.getPersistentData().put(VISIT,t);player.getAttribute(Attributes.SCALE).removeModifier(InversionEffect.SIZE);player.getAttribute(Attributes.SCALE).setBaseValue(1);player.refreshDimensions();
        teleport(player,inside,link.arrival());
    }
    public static void prepare(ServerLevel inside,ColonyTransitData.Link link,int species,int stage){
        inside.getChunkAt(link.arrival());inside.getChunkAt(link.core());
        prepareExit(inside,link);
        if(!(inside.getBlockEntity(link.core()) instanceof ColonyCoreBlockEntity)){
            inside.setBlock(link.core(),LittleLeafContent.core(species).defaultBlockState(),18);
            if(inside.getBlockEntity(link.core()) instanceof ColonyCoreBlockEntity c)c.makeInterior(species,stage);
        }
        if(inside.getBlockEntity(link.core()) instanceof ColonyCoreBlockEntity c){c.linkSource(link.source());
            // Real pantry cells replace the old air coordinate used by interior foragers.
            if(!c.abandoned())for(int x=-1;x<=1;x++)for(int z=-1;z<=1;z++){var food=link.core().offset(28+x,0,4+z);if(ColonyCoreBlockEntity.loaded(inside,food)&&inside.getBlockState(food).isAir())inside.setBlock(food,Blocks.OAK_LEAVES.defaultBlockState().setValue(net.minecraft.world.level.block.LeavesBlock.PERSISTENT,true),18);}
        }
    }
    public static void prepareExit(ServerLevel inside,ColonyTransitData.Link link){
        var a=link.arrival();var mouth=a.west(18);inside.getChunkAt(mouth);
        // Versioned, one-time migration also opens interiors generated by the first release.
        var marker=mouth.below();if(inside.getBlockState(marker).is(Blocks.SMOOTH_SANDSTONE))return;
        for(int x=-20;x<=-8;x++)for(int z=-2;z<=2;z++){
            inside.setBlock(a.offset(x,-1,z),Blocks.SMOOTH_SANDSTONE.defaultBlockState(),18);
            for(int y=0;y<4;y++)inside.setBlock(a.offset(x,y,z),x==-18&&y<3?LittleLeafContent.COLONY_EXIT.get().defaultBlockState():Blocks.AIR.defaultBlockState(),18);
        }
        var old=a.offset(0,0,-4);if(inside.getBlockState(old).is(LittleLeafContent.COLONY_EXIT.get()))inside.setBlock(old,Blocks.AIR.defaultBlockState(),18);
    }
    public static boolean invade(ServerLevel outside,ColonyCoreBlockEntity victim,ColonyInsectEntity insect){
        if(insect.level()!=outside||insect.position().distanceToSqr(net.minecraft.world.phys.Vec3.atCenterOf(victim.getBlockPos()))>(insect.enlarged()?16:3)||victim.abandoned()||victim.species()==insect.species()||insect.carrying()||insect.carryingMaterial()||victim.interior())return false;
        var data=ColonyTransitData.get(outside.getServer());var source=GlobalPos.of(outside.dimension(),victim.getBlockPos());
        if(!data.queue(source,new ColonyTransitData.Raider(insect.species(),insect.caste(),insect.getHealth()/insect.getMaxHealth())))return false;
        ColonyEffects.work(outside,victim.getBlockPos(),Blocks.DIRT.defaultBlockState(),net.minecraft.sounds.SoundEvents.GRAVEL_BREAK,insect.enlarged()?.3F:.08F);
        // Persist arrivals instead of generating or ticking unobserved dimensions/chunks.
        insect.discard();return true;
    }
    public static void releaseInvaders(ServerLevel inside,ColonyCoreBlockEntity victim){
        if(!victim.interior()||victim.abandoned()||inside.getNearestPlayer(victim.getBlockPos().getX(),victim.getBlockPos().getY(),victim.getBlockPos().getZ(),112,false)==null)return;
        var data=ColonyTransitData.get(inside.getServer());var pending=data.pending(victim.identity());if(pending.isEmpty())return;
        if(victim.queen(inside)==null)victim.birth(inside);
        if(!ColonyBudget.birth(inside))return;
        var raid=pending.get(0);var e=LittleLeafContent.type(raid.species()).create(inside);if(e==null)return;e.bind(victim.getBlockPos(),raid.caste(),true,true);e.invade();e.setHealth(e.getMaxHealth()*raid.health());
        if(!victim.placeAtEntrance(inside,e,victim.getBlockPos().offset(2,0,7)))return;
        if(inside.addFreshEntity(e)){data.consumed(victim.identity());ColonyEffects.work(inside,e.blockPosition(),Blocks.DIRT.defaultBlockState(),net.minecraft.sounds.SoundEvents.SILVERFISH_AMBIENT,.25F);}
    }
    public static void leave(ServerPlayer player){
        if(!player.level().dimension().equals(DIMENSION)||cooldown(player))return;var t=player.getPersistentData().getCompound(VISIT);
        var id=ResourceLocation.tryParse(t.getString("Dimension"));if(id==null)return;var source=player.server.getLevel(ResourceKey.create(Registries.DIMENSION,id));if(source==null)return;
        var home=BlockPos.of(t.getLong("Source"));source.getChunkAt(home);
        var destination=safeReturn(source,home);
        player.getAttribute(Attributes.SCALE).setBaseValue(Math.max(.0625,Math.min(16,t.getDouble("BaseScale"))));InversionEffect.miniature(player);
        player.getPersistentData().remove(VISIT);teleport(player,source,destination);
    }
    public static BlockPos safeReturn(ServerLevel l,BlockPos p){
        // Only the explicitly requested return neighborhood; no unbounded height/biome search.
        for(int r=1;r<=4;r++)for(int x=-r;x<=r;x++)for(int z=-r;z<=r;z++){
            if(Math.max(Math.abs(x),Math.abs(z))!=r)continue;var q=p.offset(x,0,z);
            if(ColonyCoreBlockEntity.loaded(l,q)&&l.getBlockState(q).getCollisionShape(l,q).isEmpty()&&l.getFluidState(q).isEmpty()&&!l.getBlockState(q.below()).getCollisionShape(l,q.below()).isEmpty())return q;
        }
        // Destroyed or sealed entrances still have a tiny escape pocket, keeping the saved visit usable.
        var q=p.above(16);l.setBlock(q.below(),Blocks.DIRT.defaultBlockState(),18);l.setBlock(q,Blocks.AIR.defaultBlockState(),18);return q;
    }
    private static boolean cooldown(ServerPlayer p){return p.server.overworld().getGameTime()<p.getPersistentData().getLong(COOLDOWN);}
    private static void teleport(ServerPlayer p,ServerLevel l,BlockPos q){p.getPersistentData().putLong(COOLDOWN,p.server.overworld().getGameTime()+40);p.teleportTo(l,q.getX()+.5,q.getY(),q.getZ()+.5,Set.of(),p.getYRot(),p.getXRot());}
    @SubscribeEvent public static void login(PlayerEvent.PlayerLoggedInEvent e){
        if(!(e.getEntity() instanceof ServerPlayer p)||!p.level().dimension().equals(DIMENSION)||!p.getPersistentData().contains(VISIT))return;
        var t=p.getPersistentData().getCompound(VISIT);var id=ResourceLocation.tryParse(t.getString("Dimension"));if(id==null)return;
        var link=ColonyTransitData.get(p.server).find(ResourceKey.create(Registries.DIMENSION,id),BlockPos.of(t.getLong("Source")));if(link!=null)prepareExit(p.serverLevel(),link);
    }
    @SubscribeEvent public static void clone(PlayerEvent.Clone e){if(e.getOriginal().getPersistentData().contains(VISIT))e.getEntity().getPersistentData().put(VISIT,e.getOriginal().getPersistentData().getCompound(VISIT).copy());}
    @SubscribeEvent public static void respawn(PlayerEvent.PlayerRespawnEvent e){
        if(!(e.getEntity() instanceof ServerPlayer p)||!p.getPersistentData().contains(VISIT))return;
        var t=p.getPersistentData().getCompound(VISIT);var id=ResourceLocation.tryParse(t.getString("Dimension"));var l=p.server.getLevel(DIMENSION);if(id==null||l==null)return;
        var link=ColonyTransitData.get(p.server).find(ResourceKey.create(Registries.DIMENSION,id),BlockPos.of(t.getLong("Source")));if(link==null)return;
        p.getAttribute(Attributes.SCALE).removeModifier(InversionEffect.SIZE);p.getAttribute(Attributes.SCALE).setBaseValue(1);prepare(l,link,0,0);teleport(p,l,link.arrival());
    }
}
